version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile 
    ports:
      - "8080:8080"
      - "80:80"
    container_name: "COV"
    volumes:
      - ./docker/app:/app
    environment:
      - FLASK_ENV=production
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


