version: '3'
services:
  web:
    build: 
      context: ./docker
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
      - "80:80"
    container_name: "COV"
    volumes:
      - ./docker/app:/app
    environment:
      - FLASK_ENV=production


